version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_DB=2immerse_editor
  web:
    build: .
    command: python run.py
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
