version: '2'
services:
  web:
    build: .
    command: python run.py
    volumes:
      - .:/code
    ports:
      - "8008:8000"
    networks:
        - 2immerse

networks:
  2immerse:
    driver: bridge

